#!/usr/bin/bash
# This is an importent check to run before exiting your server.
# Firstly, It installs net-tools if you do not have it.
# Secondly, checks if port 22 is allowed
# Lastly, It checks if the your public key exists in ~/.ssh/authorized_keys

# Check if net-tools is installed
if ! command -v netstat &>/dev/null; then
    echo "net-tools is not installed. Installing..."
    sudo apt update
    sudo apt install -y net-tools
else  
    echo "net-tools already exists."
fi

# Define the public key
public_key="===>!!!!!!!!!!!!!!!!!Place your public key here!!!!!!!!!!!!!!!!!!!!!!<==="
# Define colors
green='\033[0;32m'
red='\033[0;31m'
nc='\033[0m' # No Color

# Check if port 22 is allowed
if netstat -tuln | grep ":22.*LISTEN" &>/dev/null; then
    echo -e "${green}===> Port 22 is allowed.${nc}"
else
    echo -e "${red}===> Port 22 is not allowed.${nc}"
    echo -e "Allowing it ..."
    sudo ufw allow 22
    echo -e "${green}===> Port 22 is allowed.${nc}"
fi

echo -e "\t...\n\t...\n\t..."
# Check if the public key exists in ~/.ssh/authorized_keys
if sudo grep -qFx "$public_key" ~/.ssh/authorized_keys; then
    echo -e "${green}===> Your public key exists.${nc}"
else
    echo -e "${red}===> Public key does not exist.${nc}"
fi
